# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa566aa878440a23c3d4bb9fc0f6c786f601b8cd2a229138bd0be4844eb23c90fc1ab1de2c0fc35d99044f1bad97db24905f6a84593a739a7d6800d81255467

test:
  secret_key_base: 4c1f13835ecf1ac56a0f87e4c5b53c6c93237fe5680cdc675558cd0d726dad6f5572eda6e803f6ac09cc1e806a06e677952ec595776ec1c7f7b7cee44af9119e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
